### ISSUE TITLE
ipdb xxx.ipdb must be conf path

### ISSUE THREAD

**Issue by selboo** [vislee/ngx_stream_ipdb_module#1]
\# ls -l /usr/local/openresty-1.15.8.1/nginx/conf/qqwry.ipdb
-rw-r--r--@ 1 selboo  wheel  7447065 Jul 23 13:16 /usr/local/openresty-1.15.8.1/nginx/conf/qqwry.ipdb

\# pwd
/Users/selboo/github/ngx_stream_ipdb_module
\# /usr/local/openresty-1.15.8.1/nginx/sbin/nginx -t
nginx: [emerg] ipdb_reader_new("qqwry.ipdb") failed in /usr/local/openresty-1.15.8.1/nginx/conf/nginx.conf:184
nginx: configuration file /usr/local/openresty-1.15.8.1/nginx/conf/nginx.conf test failed

\# cd /usr/local/openresty-1.15.8.1/nginx/conf
\# pwd
/usr/local/openresty-1.15.8.1/nginx/conf
\# /usr/local/openresty-1.15.8.1/nginx/sbin/nginx -t
nginx: the configuration file /usr/local/openresty-1.15.8.1/nginx/conf/nginx.conf syntax is ok
nginx: configuration file /usr/local/openresty-1.15.8.1/nginx/conf/nginx.conf test is successful

**Comment by vislee** [comment]
yes, like [geoip_country](http://nginx.org/en/docs/stream/ngx_stream_geoip_module.html#geoip_country)
